### ISSUE TITLE
Letter marked in bold in: “Client Communication”

### ISSUE THREAD

**Issue by anaPiris** [Azordev/various-tasks#50]
### Explanation

In “Client Communication” in the box the title “Olive Branch Clinic” the letter is in bold.

  **Actual result: **

The box letter “Olive Branch Clinic” is in bold.

**Expected result: **

That the letter of the box “Olive Branch Clinic” is not in bold.

  *Screen size: *

     For 1440x633 screen

### Screenshots

Original:
![image](https://user-images.githubusercontent.com/66505715/164737721-b85f6b7f-82dd-4315-84ea-87816dce5088.png)

Our: 
![image](https://user-images.githubusercontent.com/66505715/164737760-79545c30-ebdd-45b2-a036-299b577d306e.png)

### Check list

Check the font color for this box.

Review for resolution 1440.

  
### References

  Source: http://spgatsbystg.wpengine.com/features/

  Our: https://wwwsimplepracticegatsbystaging.gatsbyjs.io/features/#clients

**Comment by heliomar-pena** [comment]
Hi, Leticia!, thanks for help reviewing and reporting. 
![lastscreenshot](https://user-images.githubusercontent.com/66505715/164741020-92005f23-b9cf-4a77-a9ca-b378ea92cd75.png)

In this case we can't do anything since it is a graphic resource (an image), and we receive that image from the client, we couldn't do anything to fix that problem
